services:
    bot:
        image: neechan9/bot_name_bot:latest
        restart: always
        environment:
            - DATABASE_HOST=postgres
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=postgres
            - DATABASE_NAME=DBname
            - DATABASE_URL=postgresql+psycopg://postgres:postgres@postgres:5432/DBname
        depends_on:
            - redis_fsm
            - postgres
    
    postgres:
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=DBname
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 1s
            timeout: 5s
            retries: 5
            start_period: 10s

    redis_fsm:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./redis_fsm_data:/data
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]